rules:
- mode: regex
  patterns:
    - "^[gisy][0-9]{9}$"

- mode: vendor
  patterns:
    - "Beijing Xiaomi Mobile Software Co., Ltd"
    - "Cisco Systems, Inc"
    - "MERCUSYS TECHNOLOGIES CO., LTD."
    - "MERCURY COMMUNICATION TECHNOLOGIES CO.,LTD."
    - "Mercury Systems â€“ Trusted Mission Solutions, Inc."
    - "Netis Technology Co., Ltd."
    - "Routerboard.com"
    - "Tenda Technology Co.,Ltd.Dongguan branch"
    - "TP-LINK TECHNOLOGIES CO.,LTD."
    - "Ubiquiti Inc"

- mode: vendor
  patterns:
    - "TP-Link Systems Inc"
  except:
    name_regex: ["^(WS-|DESKTOP|LAPTOP|PC|WIN-|DESKTOP-)", "(?i)MacBook|iPhone|Android"]
